### ISSUE TITLE
VS code 跑Jupyter的問題

### ISSUE THREAD

**Issue by Jimscwang** [arleigh418/python-and-Taiwan-stock-market#13]
Dear Sir :
我安裝完擴展後,一樣沒辦法執行,都顯示:找不到指定模組,請問這要怎麼解決?感謝

Log:
Error 23:30:58: DataScience Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: ImportError: DLL load failed while importing error: 找不到指定的模組。....
	at c:\Users\MT\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1023351
	at c:\Users\MT\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:695951
	at c:\Users\MT\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:696169
	at Immediate._onImmediate (c:\Users\MT\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: 'ImportError: DLL load failed while importing error: 找不到指定的模組。. \n',
  stdErr: 'Traceback (most recent call last):\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 192, in _run_module_as_main\r\n' +
    '    return _run_code(code, main_globals, None,\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 85, in _run_code\r\n' +
    '    exec(code, run_globals)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel_launcher.py", line 15, in <module>\r\n' +
    '    from ipykernel import kernelapp as app\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel\\__init__.py", line 2, in <module>\r\n' +
    '    from .connect import *\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel\\connect.py", line 10, in <module>\r\n' +
    '    import jupyter_client\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\__init__.py", line 6, in <module>\r\n' +
    '    from .asynchronous import AsyncKernelClient  # noqa\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\asynchronous\\__init__.py", line 1, in <module>\r\n' +
    '    from .client import AsyncKernelClient  # noqa\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\asynchronous\\client.py", line 6, in <module>\r\n' +
    '    from jupyter_client.channels import HBChannel\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\channels.py", line 12, in <module>\r\n' +
    '    import zmq.asyncio\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\__init__.py", line 125, in <module>\r\n' +
    '    from zmq import backend\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\__init__.py", line 32, in <module>\r\n' +
    '    raise original_error from None\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\__init__.py", line 27, in <module>\r\n' +
    '    _ns = select_backend(first)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\select.py", line 32, in select_backend\r\n' +
    '    mod = import_module(name)\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\importlib\\__init__.py", line 127, in import_module\r\n' +
    '    return _bootstrap._gcd_import(name[level:], package, level)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\cython\\__init__.py", line 6, in <module>\r\n' +
    '    from . import (\r\n' +
    'ImportError: DLL load failed while importing error: 找不到指定的模組。\r\n',
  exitCode: 1,
  reason: 'Traceback (most recent call last):\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 192, in _run_module_as_main\r\n' +
    '    return _run_code(code, main_globals, None,\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 85, in _run_code\r\n' +
    '    exec(code, run_globals)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel_launcher.py", line 15, in <module>\r\n' +
    '    from ipykernel import kernelapp as app\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel\\__init__.py", line 2, in <module>\r\n' +
    '    from .connect import *\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel\\connect.py", line 10, in <module>\r\n' +
    '    import jupyter_client\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\__init__.py", line 6, in <module>\r\n' +
    '    from .asynchronous import AsyncKernelClient  # noqa\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\asynchronous\\__init__.py", line 1, in <module>\r\n' +
    '    from .client import AsyncKernelClient  # noqa\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\asynchronous\\client.py", line 6, in <module>\r\n' +
    '    from jupyter_client.channels import HBChannel\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\channels.py", line 12, in <module>\r\n' +
    '    import zmq.asyncio\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\__init__.py", line 125, in <module>\r\n' +
    '    from zmq import backend\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\__init__.py", line 32, in <module>\r\n' +
    '    raise original_error from None\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\__init__.py", line 27, in <module>\r\n' +
    '    _ns = select_backend(first)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\select.py", line 32, in select_backend\r\n' +
    '    mod = import_module(name)\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\importlib\\__init__.py", line 127, in import_module\r\n' +
    '    return _bootstrap._gcd_import(name[level:], package, level)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\cython\\__init__.py", line 6, in <module>\r\n' +
    '    from . import (\r\n' +
    'ImportError: DLL load failed while importing error: 找不到指定的模組。\r\n'
}
Error 23:30:58: DataScience Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: ImportError: DLL load failed while importing error: 找不到指定的模組。....
	at c:\Users\MT\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:1023351
	at c:\Users\MT\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:695951
	at c:\Users\MT\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:696169
	at Immediate._onImmediate (c:\Users\MT\.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: 'ImportError: DLL load failed while importing error: 找不到指定的模組。. \n',
  stdErr: 'Traceback (most recent call last):\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 192, in _run_module_as_main\r\n' +
    '    return _run_code(code, main_globals, None,\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 85, in _run_code\r\n' +
    '    exec(code, run_globals)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel_launcher.py", line 15, in <module>\r\n' +
    '    from ipykernel import kernelapp as app\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel\\__init__.py", line 2, in <module>\r\n' +
    '    from .connect import *\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel\\connect.py", line 10, in <module>\r\n' +
    '    import jupyter_client\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\__init__.py", line 6, in <module>\r\n' +
    '    from .asynchronous import AsyncKernelClient  # noqa\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\asynchronous\\__init__.py", line 1, in <module>\r\n' +
    '    from .client import AsyncKernelClient  # noqa\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\asynchronous\\client.py", line 6, in <module>\r\n' +
    '    from jupyter_client.channels import HBChannel\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\channels.py", line 12, in <module>\r\n' +
    '    import zmq.asyncio\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\__init__.py", line 125, in <module>\r\n' +
    '    from zmq import backend\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\__init__.py", line 32, in <module>\r\n' +
    '    raise original_error from None\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\__init__.py", line 27, in <module>\r\n' +
    '    _ns = select_backend(first)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\select.py", line 32, in select_backend\r\n' +
    '    mod = import_module(name)\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\importlib\\__init__.py", line 127, in import_module\r\n' +
    '    return _bootstrap._gcd_import(name[level:], package, level)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\cython\\__init__.py", line 6, in <module>\r\n' +
    '    from . import (\r\n' +
    'ImportError: DLL load failed while importing error: 找不到指定的模組。\r\n',
  exitCode: 1,
  reason: 'Traceback (most recent call last):\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 192, in _run_module_as_main\r\n' +
    '    return _run_code(code, main_globals, None,\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\runpy.py", line 85, in _run_code\r\n' +
    '    exec(code, run_globals)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel_launcher.py", line 15, in <module>\r\n' +
    '    from ipykernel import kernelapp as app\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel\\__init__.py", line 2, in <module>\r\n' +
    '    from .connect import *\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\ipykernel\\connect.py", line 10, in <module>\r\n' +
    '    import jupyter_client\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\__init__.py", line 6, in <module>\r\n' +
    '    from .asynchronous import AsyncKernelClient  # noqa\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\asynchronous\\__init__.py", line 1, in <module>\r\n' +
    '    from .client import AsyncKernelClient  # noqa\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\asynchronous\\client.py", line 6, in <module>\r\n' +
    '    from jupyter_client.channels import HBChannel\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\jupyter_client\\channels.py", line 12, in <module>\r\n' +
    '    import zmq.asyncio\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\__init__.py", line 125, in <module>\r\n' +
    '    from zmq import backend\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\__init__.py", line 32, in <module>\r\n' +
    '    raise original_error from None\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\__init__.py", line 27, in <module>\r\n' +
    '    _ns = select_backend(first)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\select.py", line 32, in select_backend\r\n' +
    '    mod = import_module(name)\r\n' +
    '  File "C:\\Users\\MT\\AppData\\Local\\Programs\\Python\\Python38\\lib\\importlib\\__init__.py", line 127, in import_module\r\n' +
    '    return _bootstrap._gcd_import(name[level:], package, level)\r\n' +
    '  File "d:\\Trading\\env\\lib\\site-packages\\zmq\\backend\\cython\\__init__.py", line 6, in <module>\r\n' +
    '    from . import (\r\n' +
    'ImportError: DLL load failed while importing error: 找不到指定的模組。\r\n'
}

**Comment by arleigh418** [comment]
Hi 您好~
這個問題基本上可能的因素有很多，所以可能需要了解一下您的環境。
您在這之前是否已經有安裝過Anaconda? 您可以至控制台看看自己的環境是不是有多個python (包含Anaconda)。
另外也有可能是您vscode的安裝位置，您是使用預設的安裝嗎? 或是您是安裝在自選的位置例如D槽之類的?

**Comment by Jimscwang** [comment]
我後來查,好像是python3.8的問題,請問怎麼將版本降到3.7.6版??

**Comment by arleigh418** [comment]
雖然就我所知，好像有聽過降版的語法，尤其conda似乎更容易些，不過似乎常常有聽到災情。
所以通常我們都是直接卸載再重新安裝，既簡單暴力，且一定不會出錯。
如果您覺得會遺失套件要重裝很麻煩的話，像我們書中介紹的，先在您的環境中pip freeze出package包，再安裝就可以了。

**Comment by Jimscwang** [comment]
恩,直接卸載再重新安裝3.7.6版就可以用了
