### ISSUE TITLE
No module named 'Crypto' after install Crypto through "pip install Crypto".

### ISSUE THREAD

**Issue by nicolast0604** [arleigh418/python-and-Taiwan-stock-market#16]
(env) D:\python-and-Taiwan-stock-market\Trading>python 1_buy_follow_corp.py Traceback (most recent call last):   File "D:\python-and-Taiwan-stock-market\Trading\1_buy_follow_corp.py", line 4, in <module>     import utility_f as uf   File "D:\python-and-Taiwan-stock-market\Trading\utility_f.py", line 10, in <module>     from AES_Encryption.encrype_process import *   File "D:\python-and-Taiwan-stock-market\Trading\AES_Encryption\encrype_process.py", line 2, in <module>     from AES_Encryption.en_decrype import *   File "D:\python-and-Taiwan-stock-market\Trading\AES_Encryption\en_decrype.py", line 1, in <module>     from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto'

**Comment by arleigh418** [comment]
Hi, Thanks for your question. please check part3.5 (page 3-79), not install Crypto package.
