### ISSUE TITLE
stock_list.py執行錯誤

### ISSUE THREAD

**Issue by benny0130** [arleigh418/python-and-Taiwan-stock-market#30]
Hello 作者您好 ,
不好意思,我目前打第一個程式就出錯了,請參考以下畫面,我的requests / bs4 / pandas應該都有裝成功,不知道怎麼會這樣,再請您協助解惑一下感謝您

>>> #對網站進行requests，並加入指定的headers一同請求
>>> 
>>> html_data = requests.get("https://isin.twse.com.tw/isin/C_public.jsp?strMode=2",headers=headers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'requests' is not defined
>>> print(html_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'html_data' is not defined

**Comment by arleigh418** [comment]
Hi 您好, 錯誤訊息向您表示了, 他並沒有找到html_data這一個變數,尚未被定義.
這意味著您的print(html_data)應該在宣告html_data變數之前,所以導致錯誤.

程式是一行行執行下去的, 您必須先賦予html_data值,如:
`html_data = requests.get("[https://isin.twse.com.tw/isin/C_public.jsp?strMode=2",headers=headers](https://isin.twse.com.tw/isin/C_public.jsp?strMode=2%22,headers=headers))`

才可以將它print出來看.
`print(html_data)`

否則將會跳出您所貼出的錯誤.

**Comment by benny0130** [comment]
作者您好,
感謝回覆 ,
不過我有先試過一行一行key , 還有copy and paste your code.
但他還是跑出了這個error.

以上感謝


![擷取](https://user-images.githubusercontent.com/16012179/177043609-2a8655fd-d73d-4b55-a1f3-f8f5fc423907.PNG)

**Comment by arleigh418** [comment]
不好意思, 看到您的截圖才完全明白, 是我漏看了, 原因是您的requests套件沒有裝好.
這得是您的requests套件是裝在虛擬環境內, 還是原生環境內.

我初步判斷您應該是裝在虛擬環境內,但是用vscode的快捷執行他沒有吃到虛擬環境,導致找不到虛擬環境.
建議可以嘗試三個解:
1. 將stock_list.py或任何py程式搬出虛擬環境的資料夾, 不要將程式放在ENV資料夾裡面, 跟ENV資料夾擺在同一層後再執行
2. 使用cmd來執行, cd到目標虛擬環境,啟動後執行程式.
3. 想使用vscode執行,比較專業的做法,透過VSCODE設定去指定執行環境,步驟如下:
    a. 按Ctrl+Shift+P , 此時應出現一個輸入框
    b. 輸入python select interpreter , 之後您可以看看選擇列中有沒有您的虛擬環境, 如果沒有, 可以選擇新增路徑,路徑是虛擬  環境資料夾中的Scripts資料夾裡的python.exe (e.g. D:/test/env/Scripts/python.exe)
    c. kill掉當前的終端機(最下方那個終端機區塊,附近應該有一個垃圾桶符號,點一下可以kill掉) 再次用快捷鍵執行, 應就可以.

請您嘗試看看囉, 有甚麼疑問歡迎在隨時提出討論!!

**Comment by benny0130** [comment]
謝謝作者熱心回復,先前狀況已經排除,目前可以正常寫code.本書真的實戰性極高,謝謝作者撰寫本書,讓我們可以更有效的學習交易與python.謝謝您

**Comment by arleigh418** [comment]
您客氣了,有其他疑惑歡迎隨時提出討論哦~

**Comment by YZeCode** [comment]
@arleigh418 
你好，我想問stock_list.py 在CMD 執行完後，出現warning 

UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  x['上市日'] = pd.to_datetime(x['上市日'], errors='coerce')

執行結果是正常但是就會有這條訊息，再麻煩您解惑 

謝謝

**Comment by YZeCode** [comment]
問題已解決
在 x['上市日'] = pd.to_datetime(x['上市日'], format="%Y/%m/%d", errors='coerce')
需定義日期格式 
pandas預設是 日 月 年

**Comment by bensonlee25-sketch** [comment]
作者你好,
   下面是在實體環境 跑的 stock_list.py 所出現訊息.   這支stock_list.py 是下載直接跑.  requests 套件已 install.    vscode, cmd 跑都出現相同問題.    沒有頭緒如何下手.   請幫我看看.   感謝.

Traceback (most recent call last):
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\connection.py", line 969, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\util\ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\util\ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Subject Key Identifier (_ssl.c:1028)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Subject Key Identifier (_ssl.c:1028)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\requests\adapters.py", line 644, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='isin.twse.com.tw', port=443): Max retries exceeded with url: /isin/C_public.jsp?strMode=2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Subject Key Identifier (_ssl.c:1028)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Personal\Proj-trading\stock_tool\stock_list.py", line 9, in <module>
    html_data = requests.get("https://isin.twse.com.tw/isin/C_public.jsp?strMode=2",headers=headers)
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Tools\Python3.13\WPy64-31350\python\Lib\site-packages\requests\adapters.py", line 675, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='isin.twse.com.tw', port=443): Max retries exceeded with url: /isin/C_public.jsp?strMode=2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Subject Key Identifier (_ssl.c:1028)')))

**Comment by bensonlee25-sketch** [comment]
前面 stock_list 遇到 SSL: CERTIFICATE_VERIFY_FAILED, 

google 到 python 3.13 security change 相關討論 與 解決式, 如下:

https://discuss.python.org/t/python-3-13-x-ssl-security-changes/91266

https://pypi.org/project/pip-system-certs/

安裝 pip_system_certs 後, 問題已解決.

**Comment by arleigh418** [comment]
不好意思，我現在才看到這一個問題
如果我超過一周沒有回覆，請您寄信給我，或是再開一個問題串，有時候會漏掉問題。
