### ISSUE TITLE
stock_list.py寫出Excel檔出現問題

### ISSUE THREAD

**Issue by Austin-Fang-Gh** [arleigh418/python-and-Taiwan-stock-market#46]
執行stock_list.py寫出Excel出現以下問題 (D:\Trading Strategy_EX\Chapter2\是存在的，但沒有產生Excel)
，請幫忙解惑，感謝! 

Traceback (most recent call last):
  File "D:\Trading Strategy_EX\Chapter2\stock_list.py", line 44, in <module>
    x.to_excel('D:\Trading Strategy_EX\Chapter2\stock_list.xlsx')
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 2417, in to_excel
    formatter.write(
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\excel.py", line 943, in write
    writer = ExcelWriter(
  File "C:\Users\Austin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\excel\_openpyxl.py", line 57, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'

Austin

**Comment by arleigh418** [comment]
您好，我很高興收到您的提問。
您遭遇到的問題是缺乏的 openpyxl 這個套件，請您在 CMD 中安裝應該即可：
`pip install openpyxl `
or 
`pip3 install openpyxl`

**Comment by Austin-Fang-Gh** [comment]
您好，
感謝您的快速回覆，install openpyxl後問題就解決了。
Thanks & regards!
Austin
